spring.application.name: SistemaDeGestionBibliotecaria

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: juan
    password: 12345
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

properties:
  messages:
    error:
      library-does-not-exist: "La libreria no existe en la base de datos"
      name-library-exist: "El nombre de la libreria ya existe en la base de datos"
      author-does-not-exist: "El autor no existe en la base de datos"
      name-author-exist: "El nombre del autor ya existe en la base de datos"
      book-does-not-exist: "El libro no existe en la base de datos"
      name-book-exist: "El nombre del libro ya existe en la base de datos"
      isbn-book-exist: "El ISBN del libro ya existe en la base de datos"